// enemies.js
import { allItems } from "./items.js";

export const enemyData = {
  slime: {
    type: "Slime",
    levelRequirement: 1,
    hp: 20,
    maxHp: 20,
    attack: 3,
    defense: 1,
    experience: 10,
    gold: 5,
    drops: ["mana_potion"],
  },
  fungedBeast: {
    type: "Funged Beast",
    levelRequirement: 1,
    hp: 25,
    maxHp: 25,
    attack: 5,
    defense: 1,
    experience: 15,
    gold: 5,
    drops: ["health_potion"],
  },
  goblin: {
    type: "Goblin",
    levelRequirement: 2,
    hp: 30,
    maxHp: 30,
    attack: 6,
    defense: 1,
    experience: 20,
    gold: 8,
    drops: ["sword"],
  },
  wolf: {
    type: "Wolf",
    levelRequirement: 2,
    hp: 40,
    maxHp: 40,
    attack: 8,
    defense: 2,
    experience: 25,
    gold: 10,
    drops: ["health_potion"],
  },
  thief: {
    type: "Thief",
    levelRequirement: 2,
    hp: 35,
    maxHp: 35,
    attack: 7,
    defense: 1,
    experience: 22,
    gold: 12,
    drops: ["ring_agility"],
  },
  guard: {
    type: "Royal Guard",
    levelRequirement: 3,
    hp: 50,
    maxHp: 50,
    attack: 10,
    defense: 4,
    experience: 35,
    gold: 15,
    drops: ["armor"],
  },
  orc: {
    type: "Orc",
    levelRequirement: 3,
    hp: 60,
    maxHp: 60,
    attack: 12,
    defense: 4,
    experience: 40,
    gold: 20,
    drops: ["axe"],
  },
  goblin_shaman: {
    type: "Goblin Shaman",
    levelRequirement: 3,
    hp: 45,
    maxHp: 45,
    attack: 8,
    defense: 2,
    magicAttack: 12,
    experience: 38,
    gold: 18,
    drops: ["staff"],
  },
  cave_bat: {
    type: "Cave Bat",
    levelRequirement: 1,
    hp: 25,
    maxHp: 25,
    attack: 5,
    defense: 0,
    experience: 15,
    gold: 5,
    drops: ["mana_potion"],
  },
  cave_bear: {
    type: "Cave Bear",
    levelRequirement: 3,
    hp: 70,
    maxHp: 70,
    attack: 15,
    defense: 5,
    experience: 50,
    gold: 25,
    drops: ["health_potion"],
  },
  giant_spider: {
    type: "Giant Spider",
    levelRequirement: 3,
    hp: 55,
    maxHp: 55,
    attack: 11,
    defense: 3,
    experience: 50,
    gold: 22,
    drops: ["ring_strength"],
  },
  cave_troll: {
    type: "Cave Troll",
    levelRequirement: 4,
    hp: 80,
    maxHp: 80,
    attack: 18,
    defense: 6,
    experience: 60,
    gold: 30,
    drops: ["chainmail"],
  },
  stone_golem: {
    type: "Stone Golem",
    levelRequirement: 5,
    hp: 100,
    maxHp: 100,
    attack: 20,
    defense: 10,
    experience: 80,
    gold: 40,
    drops: ["ring_strength"],
  },
  ancient_guardian: {
    type: "Ancient Guardian",
    levelRequirement: 4,
    hp: 90,
    maxHp: 90,
    attack: 16,
    defense: 8,
    magicAttack: 14,
    experience: 80,
    gold: 35,
    drops: ["chainmail"],
  },
  mountain_giant: {
    type: "Mountain Giant",
    levelRequirement: 5,
    hp: 120,
    maxHp: 120,
    attack: 22,
    defense: 7,
    experience: 100,
    gold: 45,
    drops: ["axe"],
  },
  wyvern: {
    type: "Wyvern",
    levelRequirement: 5,
    hp: 95,
    maxHp: 95,
    attack: 18,
    defense: 5,
    experience: 80,
    gold: 40,
    drops: ["robe"],
  },
  treasure_guardian: {
    type: "Treasure Guardian",
    levelRequirement: 5,
    hp: 110,
    maxHp: 110,
    attack: 19,
    defense: 9,
    magicAttack: 16,
    experience: 100,
    gold: 100,
    drops: ["chainmail", "divine_sword", "plate_armor"],
  },
  beholder: {
    type: "Beholder",
    levelRequirement: 5,
    hp: 100,
    maxHp: 100,
    attack: 20,
    defense: 7,
    experience: 100,
    gold: 40,
    drops: ["katana"],
  },

  zombie: {
    type: "Zombie",
    levelRequirement: 2,
    hp: 50,
    maxHp: 50,
    attack: 10,
    defense: 3,
    experience: 40,
    gold: 20,
    drops: ["big_health_potion"],
  },
  vampire: {
    type: "Vampire",
    levelRequirement: 3,
    hp: 80,
    maxHp: 80,
    attack: 15,
    defense: 5,
    experience: 60,
    gold: 30,
    drops: ["elixir_potion"],
  },
  squeletor: {
    type: "Squeletor",
    levelRequirement: 2,
    hp: 70,
    maxHp: 70,
    attack: 12,
    defense: 4,
    experience: 55,
    gold: 25,
    drops: ["hammer"],
  },
  warlock: {
    type: "Warlock",
    levelRequirement: 3,
    hp: 90,
    maxHp: 90,
    attack: 14,
    defense: 6,
    magicAttack: 18,
    experience: 70,
    gold: 35,
    drops: ["wand"],
  },
  imp: {
    type: "Imp",
    levelRequirement: 2,
    hp: 40,
    maxHp: 40,
    attack: 8,
    defense: 2,
    experience: 30,
    gold: 15,
    drops: ["gown"],
  },
  linchorn: {
    type: "Linchorn",
    levelRequirement: 5,
    hp: 110,
    maxHp: 110,
    attack: 20,
    defense: 8,
    experience: 100,
    gold: 45,
    drops: ["katana"],
  },
  hydra: {
    type: "Hydra",
    levelRequirement: 6,
    hp: 150,
    maxHp: 150,
    attack: 22,
    defense: 9,
    experience: 120,
    gold: 60,
    drops: ["plate_armor"],
  },
  centaurus: {
    type: "Centaurus",
    levelRequirement: 5,
    hp: 130,
    maxHp: 130,
    attack: 18,
    defense: 7,
    experience: 100,
    gold: 55,
    drops: ["elemental_wand"],
  },
  chimera: {
    type: "Chimera",
    levelRequirement: 6,
    hp: 140,
    maxHp: 140,
    attack: 20,
    defense: 8,
    experience: 110,
    gold: 58,
    drops: ["divine_sword"],
  },
  cultist: {
    type: "Cultist",
    levelRequirement: 4,
    hp: 85,
    maxHp: 85,
    attack: 13,
    defense: 5,
    magicAttack: 15,
    experience: 75,
    gold: 38,
    drops: ["bless_staff"],
  },
  drider: {
    type: "Drider",
    levelRequirement: 5,
    hp: 120,
    maxHp: 120,
    attack: 17,
    defense: 6,
    experience: 100,
    gold: 42,
    drops: ["arcane_robe"],
  },
  kraken: {
    type: "Kraken",
    levelRequirement: 10,
    hp: 320,
    maxHp: 320,
    attack: 30,
    defense: 12,
    magicAttack: 20,
    experience: 350,
    gold: 220,
    drops: ["trident", "sea_armor"],
  },
  sea_serpent: {
    type: "Sea Serpent",
    levelRequirement: 9,
    hp: 290,
    maxHp: 290,
    attack: 27,
    defense: 10,
    magicAttack: 18,
    experience: 310,
    gold: 200,
    drops: ["water_staff", "aqua_robe"],
  },
  medusa: {
    type: "Medusa",
    levelRequirement: 8,
    hp: 260,
    maxHp: 260,
    attack: 25,
    defense: 9,
    magicAttack: 22,
    experience: 280,
    gold: 180,
    drops: ["serpent_sword", "stone_armor"],
  },
  mermaid: {
    type: "Mermaid",
    levelRequirement: 7,
    hp: 240,
    maxHp: 240,
    attack: 22,
    defense: 8,
    magicAttack: 24,
    experience: 260,
    gold: 170,
    drops: ["ocean_staff", "coral_robe"],
  },
  pirate: {
    type: "Pirate",
    levelRequirement: 6,
    hp: 200,
    maxHp: 200,
    attack: 21,
    defense: 7,
    experience: 220,
    gold: 150,
    drops: ["cutlass", "leather_armor"],
  },
  pirate_captain: {
    type: "Pirate Captain",
    levelRequirement: 8,
    hp: 270,
    maxHp: 270,
    attack: 26,
    defense: 9,
    experience: 300,
    gold: 190,
    drops: ["captain_sword", "captain_coat"],
  },
  Inferno_elemental: {
    type: "Inferno Elemental",
    levelRequirement: 9,
    hp: 280,
    maxHp: 280,
    attack: 28,
    defense: 11,
    magicAttack: 25,
    experience: 320,
    gold: 210,
    drops: ["flame_staff", "fire_robe"],
  },
  gorilla_warrior: {
    type: "Gorilla Warrior",
    levelRequirement: 7,
    hp: 220,
    maxHp: 220,
    attack: 23,
    defense: 8,
    experience: 240,
    gold: 160,
    drops: ["giant_club", "jungle_armor"],
  },
  jungle_tiger: {
    type: "Jungle Tiger",
    levelRequirement: 6,
    hp: 210,
    maxHp: 210,
    attack: 20,
    defense: 7,
    experience: 230,
    gold: 155,
    drops: ["tiger_blade", "leather_armor"],
  },
  vine_serpent: {
    type: "Vine Serpent",
    levelRequirement: 8,
    hp: 250,
    maxHp: 250,
    attack: 24,
    defense: 9,
    magicAttack: 20,
    experience: 270,
    gold: 175,
    drops: ["vine_whip", "nature_robe"],
  },
  jungle_spirit: {
    type: "Jungle Spirit",
    levelRequirement: 9,
    hp: 300,
    maxHp: 300,
    attack: 29,
    defense: 10,
    magicAttack: 28,
    experience: 330,
    gold: 215,
    drops: ["spirit_staff", "ethereal_robe"],
  },
  diablo: {
    type: "Diablo",
    levelRequirement: 10,
    hp: 350,
    maxHp: 350,
    attack: 32,
    defense: 13,
    magicAttack: 30,
    experience: 400,
    gold: 250,
    drops: ["demon_blade", "dark_armor"],
  },
  dragon: {
    type: "Dragon",
    levelRequirement: 10,
    hp: 300,
    maxHp: 300,
    attack: 35,
    defense: 10,
    magicAttack: 22,
    experience: 300,
    gold: 200,
    drops: ["ring_of_knowledge", "staff", "robe"],
  },

  dragon_king: {
    type: "Dragon",
    levelRequirement: 10,
    hp: 1000,
    maxHp: 1000,
    attack: 50,
    defense: 20,
    magicAttack: 50,
    experience: 1000,
    gold: 1000,
    drops: ["saint_grail", "excalibur", "dragon_armor"],
  },

  genie: {
    type: "Genie",
    levelRequirement: 10,
    hp: 250,
    maxHp: 250,
    attack: 20,
    defense: 5,
    magicAttack: 40,
    experience: 300,
    gold: 200,
    drops: ["ring_of_wisdom", "magic_lamp"],
  },
 
  gremlin: {
    type: "Gremlin",
    levelRequirement: 4,
    hp: 75,
    maxHp: 75,
    attack: 14,
    defense: 4,
    experience: 65,
    gold: 28,
    drops: ["dagger"],
  },

  dwarf_warrior: {
    type: "Dwarf Warrior",
    levelRequirement: 4,
    hp: 95,
    maxHp: 95,
    attack: 16,
    defense: 6,
    experience: 70,
    gold: 32,
    drops: ["war_hammer"],
  },

  pegasus: {
    type: "Pegasus",
    levelRequirement: 6,
    hp: 130,
    maxHp: 130,
    attack: 18,
    defense: 5,
    experience: 100,
    gold: 50,
    drops: ["light_armor"],
  },

  tent: {
    type: "Tent",
    levelRequirement: 5,
    hp: 110,
    maxHp: 110,
    attack: 15,
    defense: 7,
    experience: 100,
    gold: 40,
    drops: ["healing_staff"],
  },

  dark_knight: {
    type: "Dark Knight",
    levelRequirement: 7,
    hp: 160,
    maxHp: 160,
    attack: 22,
    defense: 9,
    experience: 160,
    gold: 60,
    drops: ["dark_sword", "dark_shield"],
  },

  sand_worm: {
    type: "Sand Worm",
    levelRequirement: 8,
    hp: 200,
    maxHp: 200,
    attack: 25,
    defense: 8,
    experience: 200,
    gold: 70,
    drops: ["desert_armor"],
  },

  lava_golem: {
    type: "Lava Golem",
    levelRequirement: 9,
    hp: 220,
    maxHp: 220,
    attack: 28,
    defense: 10,
    experience: 220,
    gold: 80,
    drops: ["lava_sword", "fire_shield"],
  },

  pyro_elemental: {
    type: "Pyro Elemental",
    levelRequirement: 10,
    hp: 250,
    maxHp: 250,
    attack: 30,
    defense: 12,
    magicAttack: 35,
    experience: 250,
    gold: 90,
    drops: ["pyro_staff", "flame_robe"],
  },

  inferno_dragon: {
    type: "Inferno Dragon",
    levelRequirement: 10,
    hp: 300,
    maxHp: 300,
    attack: 40,
    defense: 15,
    magicAttack: 30,
    experience: 300,
    gold: 120,
    drops: ["inferno_blade", "dragon_scale_armor"],
  },
  

};