// enemies.js
import { allItems } from "./items.js";

export const enemyData = {
  slime: {
    type: "Slime",
    levelRequirement: 1,
    hp: 20,
    maxHp: 20,
    attack: 3,
    defense: 1,
    experience: 10,
    gold: 5,
    drops: ["mana_potion"],
    img: "img/enemies/slime.png",
  },
  fungedBeast: {
    type: "Funged Beast",
    levelRequirement: 1,
    hp: 25,
    maxHp: 25,
    attack: 5,
    defense: 1,
    experience: 15,
    gold: 5,
    drops: ["health_potion"],
    img: "img/enemies/fungedBeast.png",
  },
  goblin: {
    type: "Goblin",
    levelRequirement: 2,
    hp: 30,
    maxHp: 30,
    attack: 6,
    defense: 1,
    experience: 20,
    gold: 8,
    drops: ["sword"],
    img: "img/enemies/goblin.png",
  },
  wolf: {
    type: "Wolf",
    levelRequirement: 2,
    hp: 50,
    maxHp: 50,
    attack: 8,
    defense: 2,
    experience: 30,
    gold: 10,
    drops: ["health_potion"],
    img: "img/enemies/wolf.png",
  },
  thief: {
    type: "Thief",
    levelRequirement: 2,
    hp: 35,
    maxHp: 35,
    attack: 7,
    defense: 1,
    experience: 22,
    gold: 12,
    drops: ["ring_agility"],
    img: "img/enemies/thief.png",
  },
  guard: {
    type: "Royal Guard",
    levelRequirement: 3,
    hp: 80,
    maxHp: 80,
    attack: 10,
    defense: 4,
    experience: 60,
    gold: 15,
    drops: ["armor"],
    img: "img/enemies/guard.png",
  },
  orc: {
    type: "Orc",
    levelRequirement: 3,
    hp: 100,
    maxHp: 100,
    attack: 12,
    defense: 6,
    experience: 100,
    gold: 20,
    drops: ["axe"],
    img: "img/enemies/orc.png",
  },
  goblin_shaman: {
    type: "Goblin Shaman",
    levelRequirement: 3,
    hp: 85,
    maxHp: 85,
    attack: 10,
    defense: 5,
    magicAttack: 12,
    experience: 60,
    gold: 18,
    drops: ["staff"],
    img: "img/enemies/goblin_shaman.png",
  },
  elf: {
    type: "elf",
    levelRequirement: 2,
    hp: 100,
    maxHp: 100,
    attack: 10,
    defense: 5,
    magicAttack: 12,
    experience: 80,
    gold: 60,
    drops: ["staff"],
    img: "img/enemies/elf.png",
  },
  cave_bat: {
    type: "Cave Bat",
    levelRequirement: 1,
    hp: 25,
    maxHp: 25,
    attack: 5,
    defense: 1,
    experience: 15,
    gold: 5,
    drops: ["mana_potion"],
    img: "img/enemies/cave_bat.png",
  },
  cave_bear: {
    type: "Cave Bear",
    levelRequirement: 3,
    hp: 120,
    maxHp: 120,
    attack: 15,
    defense: 8,
    experience: 100,
    gold: 25,
    drops: ["health_potion"],
    img: "img/enemies/cave_bear.png",
  },
  giant_spider: {
    type: "Giant Spider",
    levelRequirement: 3,
    hp: 155,
    maxHp: 155,
    attack: 11,
    defense: 3,
    experience: 150,
    gold: 22,
    drops: ["ring_strength"],
    img: "img/enemies/giant_spider.png",
  },
  cave_troll: {
    type: "Cave Troll",
    levelRequirement: 4,
    hp: 180,
    maxHp: 180,
    attack: 18,
    defense: 6,
    experience: 180,
    gold: 30,
    drops: ["chainmail"],
    img: "img/enemies/cave_troll.png",
  },
  stone_golem: {
    type: "Stone Golem",
    levelRequirement: 5,
    hp: 200,
    maxHp: 200,
    attack: 20,
    defense: 10,
    experience: 200,
    gold: 40,
    drops: ["ring_strength"],
    img: "img/enemies/stone_golem.png",
  },
  ancient_guardian: {
    type: "Ancient Guardian",
    levelRequirement: 4,
    hp: 120,
    maxHp: 120,
    attack: 16,
    defense: 8,
    magicAttack: 14,
    experience: 100,
    gold: 35,
    drops: ["chainmail"],
    img: "img/enemies/ancient_guardian.png",
  },
  mountain_giant: {
    type: "Mountain Giant",
    levelRequirement: 5,
    hp: 400,
    maxHp: 400,
    attack: 30,
    defense: 15,
    experience: 400,
    gold: 100,
    drops: ["axe"],
    img: "img/enemies/mountain_giant.png",
  },
  wyvern: {
    type: "Wyvern",
    levelRequirement: 5,
    hp: 220,
    maxHp: 220,
    attack: 18,
    defense: 8,
    experience: 220,
    gold: 100,
    drops: ["robe"],
    img: "img/enemies/wyvern.png",
  },
  treasure_guardian: {
    type: "Treasure Guardian",
    levelRequirement: 5,
    hp: 350,
    maxHp: 350,
    attack: 25,
    defense: 20,
    magicAttack: 20,
    experience: 350,
    gold: 100,
    drops: ["chainmail", "divine_sword", "plate_armor"],
    img: "img/enemies/treasure_guardian.png",
  },
  beholder: {
    type: "Beholder",
    levelRequirement: 5,
    hp: 100,
    maxHp: 100,
    attack: 20,
    defense: 7,
    experience: 100,
    gold: 70,
    drops: ["katana"],
    img: "img/enemies/beholder.png",
  },

  zombie: {
    type: "Zombie",
    levelRequirement: 2,
    hp: 50,
    maxHp: 50,
    attack: 10,
    defense: 3,
    experience: 40,
    gold: 20,
    drops: ["big_health_potion"],
    img: "img/enemies/zombie.png",
  },
  vampire: {
    type: "Vampire",
    levelRequirement: 3,
    hp: 150,
    maxHp: 150,
    attack: 15,
    defense: 5,
    experience: 150,
    gold: 30,
    drops: ["elixir_potion"],
    img: "img/enemies/vampire.png",
  },
  squeletor: {
    type: "Squeletor",
    levelRequirement: 2,
    hp: 70,
    maxHp: 70,
    attack: 12,
    defense: 4,
    experience: 55,
    gold: 25,
    drops: ["hammer"],
    img: "img/enemies/squeletor.png",
  },
  warlock: {
    type: "Warlock",
    levelRequirement: 3,
    hp: 90,
    maxHp: 90,
    attack: 14,
    defense: 6,
    magicAttack: 18,
    experience: 70,
    gold: 35,
    drops: ["wand"],
    img: "img/enemies/warlock.png",

  },
  imp: {
    type: "Imp",
    levelRequirement: 2,
    hp: 40,
    maxHp: 40,
    attack: 8,
    defense: 2,
    experience: 30,
    gold: 15,
    drops: ["gown"],
    img: "img/enemies/imp.png",
  },
  linchorn: {
    type: "Linchorn",
    levelRequirement: 5,
    hp: 210,
    maxHp: 210,
    attack: 20,
    defense: 8,
    experience: 210,
    gold: 45,
    drops: ["katana"],
    img: "img/enemies/linchorn.png",
  },
  hydra: {
    type: "Hydra",
    levelRequirement: 6,
    hp: 550,
    maxHp: 550,
    attack: 25,
    defense: 18,
    experience: 550,
    gold: 200,
    drops: ["plate_armor"],
    img: "img/enemies/hydra.png",
  },
  centaurus: {
    type: "Centaurus",
    levelRequirement: 5,
    hp: 130,
    maxHp: 130,
    attack: 18,
    defense: 7,
    experience: 100,
    gold: 55,
    drops: ["elemental_wand"],
    img: "img/enemies/centaurus.png",
  },
  chimera: {
    type: "Chimera",
    levelRequirement: 6,
    hp: 440,
    maxHp: 440,
    attack: 20,
    defense: 10,
    experience: 440,
    gold: 158,
    drops: ["divine_sword"],
    img: "img/enemies/chimera.png",
  },
  cultist: {
    type: "Cultist",
    levelRequirement: 4,
    hp: 85,
    maxHp: 85,
    attack: 13,
    defense: 5,
    magicAttack: 15,
    experience: 75,
    gold: 38,
    drops: ["bless_staff"],
    img: "img/enemies/cultist.png",
  },
  drider: {
    type: "Drider",
    levelRequirement: 5,
    hp: 320,
    maxHp: 320,
    attack: 17,
    defense: 6,
    experience: 300,
    gold: 142,
    drops: ["arcane_robe"],
    img: "img/enemies/drider.png",
  },
  kraken: {
    type: "Kraken",
    levelRequirement: 10,
    hp: 550,
    maxHp: 550,
    attack: 50,
    defense: 32,
    magicAttack: 20,
    experience: 550,
    gold: 220,
    drops: ["trident", "sea_armor"],
    img: "img/enemies/kraken.png",
  },
  sea_serpent: {
    type: "Sea Serpent",
    levelRequirement: 9,
    hp: 390,
    maxHp: 390,
    attack: 27,
    defense: 10,
    magicAttack: 18,
    experience: 390,
    gold: 200,
    drops: ["water_staff", "aqua_robe"],
    img: "img/enemies/sea_serpent.png",
  },
  medusa: {
    type: "Medusa",
    levelRequirement: 8,
    hp: 360,
    maxHp: 360,
    attack: 25,
    defense: 15,
    magicAttack: 30,
    experience: 360,
    gold: 280,
    drops: ["serpent_sword", "stone_armor"],
    img: "img/enemies/medusa.png",
  },
  mermaid: {
    type: "Mermaid",
    levelRequirement: 7,
    hp: 440,
    maxHp: 440,
    attack: 22,
    defense: 8,
    magicAttack: 24,
    experience: 440,
    gold: 170,
    drops: ["ocean_staff", "coral_robe"],
    img: "img/enemies/mermaid.png",
  },
  pirate: {
    type: "Pirate",
    levelRequirement: 6,
    hp: 200,
    maxHp: 200,
    attack: 21,
    defense: 7,
    experience: 220,
    gold: 150,
    drops: ["cutlass", "leather_armor"],
    img: "img/enemies/pirate.png",
  },
  pirate_captain: {
    type: "Pirate Captain",
    levelRequirement: 8,
    hp: 370,
    maxHp: 370,
    attack: 26,
    defense: 9,
    experience: 300,
    gold: 190,
    drops: ["captain_sword", "captain_coat"],
    img: "img/enemies/pirate_captain.png",
  },
  Inferno_elemental: {
    type: "Inferno Elemental",
    levelRequirement: 9,
    hp: 280,
    maxHp: 280,
    attack: 28,
    defense: 11,
    magicAttack: 25,
    experience: 320,
    gold: 210,
    drops: ["flame_staff", "fire_robe"],
    img: "img/enemies/inferno_elemental.png",
  },
  gorilla_warrior: {
    type: "Gorilla Warrior",
    levelRequirement: 7,
    hp: 220,
    maxHp: 220,
    attack: 23,
    defense: 8,
    experience: 240,
    gold: 160,
    drops: ["giant_club", "jungle_armor"],
    img: "img/enemies/gorilla_warrior.png",
  },
  jungle_tiger: {
    type: "Jungle Tiger",
    levelRequirement: 6,
    hp: 210,
    maxHp: 210,
    attack: 20,
    defense: 7,
    experience: 230,
    gold: 155,
    drops: ["tiger_blade", "leather_armor"],
    img: "img/enemies/jungle_tiger.png",
  },
  vine_serpent: {
    type: "Vine Serpent",
    levelRequirement: 8,
    hp: 250,
    maxHp: 250,
    attack: 24,
    defense: 9,
    magicAttack: 20,
    experience: 270,
    gold: 175,
    drops: ["vine_whip", "nature_robe"],
    img: "img/enemies/vine_serpent.png",
  },
  jungle_spirit: {
    type: "Jungle Spirit",
    levelRequirement: 9,
    hp: 300,
    maxHp: 300,
    attack: 29,
    defense: 10,
    magicAttack: 28,
    experience: 330,
    gold: 215,
    drops: ["spirit_staff", "ethereal_robe"],
    img: "img/enemies/jungle_spirit.png",
  },
  diablo: {
    type: "Diablo",
    levelRequirement: 10,
    hp: 750,
    maxHp: 750,
    attack: 52,
    defense: 33,
    magicAttack: 50,
    experience: 700,
    gold: 350,
    drops: ["demon_blade", "dark_armor"],
    img: "img/enemies/diablo.png",
  },
  dragon: {
    type: "Dragon",
    levelRequirement: 10,
    hp: 1000,
    maxHp: 1000,
    attack: 55,
    defense: 40,
    magicAttack: 52,
    experience: 800,
    gold: 400,
    drops: ["ring_of_knowledge", "staff", "robe"],
    img: "img/enemies/dragon.png",
  },

  dragon_king: {
    isBoss: true,
    type: "Dragon",
    levelRequirement: 10,
    hp: 3000,
    maxHp: 3000,
    attack: 100,
    defense: 50,
    magicAttack: 50,
    experience: 3000,
    gold: 1000,
    drops: ["saint_grail", "excalibur", "dragon_armor"],
    img: "img/enemies/dragon_king.png",
  },

  genie: {
    type: "Genie",
    levelRequirement: 10,
    hp: 250,
    maxHp: 250,
    attack: 20,
    defense: 5,
    magicAttack: 40,
    experience: 300,
    gold: 200,
    drops: ["ring_of_wisdom", "magic_lamp"],
    img: "img/enemies/genie.png",
  },

  gremlin: {
    type: "Gremlin",
    levelRequirement: 4,
    hp: 75,
    maxHp: 75,
    attack: 14,
    defense: 4,
    experience: 65,
    gold: 28,
    drops: ["dagger"],
    img: "img/enemies/gremlin.png",
  },

  dwarf_warrior: {
    type: "Dwarf Warrior",
    levelRequirement: 4,
    hp: 95,
    maxHp: 95,
    attack: 16,
    defense: 6,
    experience: 70,
    gold: 32,
    drops: ["war_hammer"],
    img: "img/enemies/dwarf_warrior.png",
  },

  pegasus: {
    type: "Pegasus",
    levelRequirement: 3,
    hp: 130,
    maxHp: 130,
    attack: 18,
    defense: 5,
    experience: 100,
    gold: 50,
    drops: ["light_armor"],
    img: "img/enemies/pegasus.png",
  },

  tent: {
    type: "Tent",
    levelRequirement: 5,
    hp: 210,
    maxHp: 210,
    attack: 15,
    defense: 7,
    experience: 200,
    gold: 100,
    drops: ["healing_staff"],
    img: "img/enemies/tent.png",
  },

  dark_knight: {
    type: "Dark Knight",
    levelRequirement: 7,
    hp: 260,
    maxHp: 260,
    attack: 22,
    defense: 15,
    experience: 300,
    gold: 60,
    drops: ["dark_sword", "dark_shield"],
    img: "img/enemies/dark_knight.png",
  },

  sand_worm: {
    type: "Sand Worm",
    levelRequirement: 8,
    hp: 200,
    maxHp: 200,
    attack: 25,
    defense: 8,
    experience: 200,
    gold: 70,
    drops: ["desert_armor"],
    img: "img/enemies/sand_worm.png",
  },

  lava_golem: {
    type: "Lava Golem",
    levelRequirement: 9,
    hp: 220,
    maxHp: 220,
    attack: 28,
    defense: 10,
    experience: 220,
    gold: 80,
    drops: ["lava_sword", "fire_shield"],
    img: "img/enemies/lava_golem.png",
  },

  pyro_elemental: {
    type: "Pyro Elemental",
    levelRequirement: 10,
    hp: 350,
    maxHp: 350,
    attack: 30,
    defense: 12,
    magicAttack: 35,
    experience: 350,
    gold: 90,
    drops: ["pyro_staff", "flame_robe"],
    img: "img/enemies/pyro_elemental.png",

  },

  inferno_dragon: {
    isBoss: true,
    type: "Inferno Dragon",
    levelRequirement: 10,
    hp: 1000,
    maxHp: 1000,
    attack: 50,
    defense: 15,
    magicAttack: 30,
    experience: 800,
    gold: 800,
    drops: ["inferno_blade", "dragon_scale_armor"],
    img: "img/enemies/inferno_dragon.png",
  },


  //bosses
  forest_titan: {
    isBoss: true,
    type: "Forest Titan",
    levelRequirement: 8,
    hp: 800,
    maxHp: 800,
    attack: 40,
    defense: 15,
    magicAttack: 30,
    experience: 800,
    gold: 120,
    drops: ["inferno_blade", "dragon_scale_armor"],
    img: "img/enemies/forest_titan.png",
  },
  cave_devourer: {
    isBoss: true,
    type: "Cave Devourer",
    levelRequirement: 8,
    hp: 800,
    maxHp: 800,
    attack: 40,
    defense: 15,
    magicAttack: 30,
    experience: 800,
    gold: 120,
    drops: ["inferno_blade", "dragon_scale_armor"],
    img: "img/enemies/cave_devourer.png",
  },
  mountain_colossus: {
    isBoss: true,
    type: "Mountain Colossus",
    levelRequirement: 8,
    hp: 800,
    maxHp: 800,
    attack: 40,
    defense: 15,
    magicAttack: 30,
    experience: 800,
    gold: 120,
    drops: ["inferno_blade", "dragon_scale_armor"],
    img: "img/enemies/mountain_colossus.png",
  },
  ancient_construct: {
    isBoss: true,
    type: "Ancient Construct",
    levelRequirement: 8,
    hp: 800,
    maxHp: 800,
    attack: 40,
    defense: 15,
    magicAttack: 30,
    experience: 800,
    gold: 120,
    drops: ["inferno_blade", "dragon_scale_armor"],
    img: "img/enemies/ancient_construct.png",
  },
  swamp_abominatinon: {
    isBoss: true,
    type: "Swamp Abomination",
    levelRequirement: 8,
    hp: 800,
    maxHp: 800,
    attack: 40,
    defense: 15,
    magicAttack: 30,
    experience: 300,
    gold: 120,
    drops: ["inferno_blade", "dragon_scale_armor"],
    img: "img/enemies/swamp_abomination.png",
  },

  frost_wyrm: {
    isBoss: true,
    type: "Frost Wyrm",
    levelRequirement: 8,
    hp: 800,
    maxHp: 800,
    attack: 40,
    defense: 15,
    magicAttack: 30,
    experience: 800,
    gold: 120,
    drops: ["inferno_blade", "dragon_scale_armor"],
    img: "img/enemies/frost_wyrm.png",
  },

};