// enemies.js
import { allItems } from "./items.js";

export const enemyData = {
  slime: {
    type: "Slime",
    levelRequirement: 1,
    hp: 20,
    maxHp: 20,
    attack: 3,
    defense: 1,
    experience: 10,
    gold: 5,
    drops: ["mana_potion"],
    // SPEC-1223: humor seco, primer encuentro (mismo gating que narratorLine de jefe).
    narratorLine: "El slime te mira. Vos lo mirás a él. Ninguno de los dos parece muy convencido de que esto vaya a ser una pelea memorable.",
    img: "img/enemies/slime.webp",
  },
  fungedBeast: {
    type: "Funged Beast",
    levelRequirement: 1,
    hp: 25,
    maxHp: 25,
    attack: 5,
    defense: 1,
    experience: 15,
    gold: 5,
    drops: ["health_potion"],
    img: "img/enemies/fungedBeast.webp",
  },
  goblin: {
    type: "Goblin",
    levelRequirement: 2,
    hp: 30,
    maxHp: 30,
    attack: 6,
    defense: 1,
    experience: 20,
    gold: 8,
    drops: ["sword"],
    narratorLine: "El goblin blande su arma como si el destino del mundo dependiera de este callejón. Nadie le avisó que no es así.",
    img: "img/enemies/goblin.webp",
  },
  wolf: {
    type: "Wolf",
    levelRequirement: 2,
    hp: 50,
    maxHp: 50,
    attack: 8,
    defense: 2,
    experience: 30,
    gold: 10,
    drops: ["health_potion"],
    img: "img/enemies/wolf.webp",
  },
  thief: {
    type: "Thief",
    levelRequirement: 2,
    hp: 35,
    maxHp: 35,
    attack: 7,
    defense: 1,
    experience: 22,
    gold: 12,
    drops: ["ring_agility"],
    narratorLine: "El ladrón te evalúa de arriba abajo, calculando cuánto valés. A juzgar por su cara, la respuesta no lo entusiasma.",
    img: "img/enemies/thief.webp",
  },
  guard: {
    type: "Royal Guard",
    levelRequirement: 3,
    hp: 80,
    maxHp: 80,
    attack: 10,
    defense: 4,
    experience: 60,
    gold: 15,
    drops: ["armor"],
    img: "img/enemies/guard.webp",
  },
  orc: {
    type: "Orc",
    levelRequirement: 3,
    hp: 100,
    maxHp: 100,
    attack: 12,
    defense: 6,
    experience: 100,
    gold: 20,
    drops: ["axe"],
    img: "img/enemies/orc.webp",
  },
  goblin_shaman: {
    type: "Goblin Shaman",
    levelRequirement: 3,
    hp: 85,
    maxHp: 85,
    attack: 10,
    defense: 5,
    magicAttack: 12,
    experience: 60,
    gold: 18,
    drops: ["staff"],
    img: "img/enemies/goblin_shaman.webp",
  },
  elf: {
    type: "elf",
    levelRequirement: 2,
    hp: 100,
    maxHp: 100,
    attack: 10,
    defense: 5,
    magicAttack: 12,
    experience: 80,
    gold: 60,
    drops: ["staff"],
    img: "img/enemies/elf.webp",
  },
  cave_bat: {
    type: "Cave Bat",
    levelRequirement: 1,
    hp: 25,
    maxHp: 25,
    attack: 5,
    defense: 1,
    experience: 15,
    gold: 5,
    drops: ["mana_potion"],
    img: "img/enemies/cave_bat.webp",
  },
  cave_bear: {
    type: "Cave Bear",
    levelRequirement: 3,
    hp: 120,
    maxHp: 120,
    attack: 15,
    defense: 8,
    experience: 100,
    gold: 25,
    drops: ["health_potion"],
    img: "img/enemies/cave_bear.webp",
  },
  giant_spider: {
    type: "Giant Spider",
    levelRequirement: 3,
    hp: 155,
    maxHp: 155,
    attack: 11,
    defense: 3,
    experience: 150,
    gold: 22,
    drops: ["ring_strength"],
    img: "img/enemies/giant_spider.webp",
  },
  cave_troll: {
    type: "Cave Troll",
    levelRequirement: 4,
    hp: 180,
    maxHp: 180,
    attack: 18,
    defense: 6,
    experience: 180,
    gold: 30,
    drops: ["chainmail"],
    img: "img/enemies/cave_troll.webp",
  },
  stone_golem: {
    type: "Stone Golem",
    levelRequirement: 5,
    hp: 200,
    maxHp: 200,
    attack: 20,
    defense: 10,
    experience: 200,
    gold: 40,
    drops: ["ring_strength"],
    img: "img/enemies/stone_golem.webp",
  },
  ancient_guardian: {
    type: "Ancient Guardian",
    levelRequirement: 4,
    hp: 120,
    maxHp: 120,
    attack: 16,
    defense: 8,
    magicAttack: 14,
    experience: 100,
    gold: 35,
    drops: ["chainmail"],
    img: "img/enemies/ancient_guardian.webp",
  },
  mountain_giant: {
    type: "Mountain Giant",
    levelRequirement: 5,
    hp: 400,
    maxHp: 400,
    attack: 30,
    defense: 15,
    experience: 400,
    gold: 100,
    drops: ["axe"],
    img: "img/enemies/mountain_giant.webp",
  },
  wyvern: {
    type: "Wyvern",
    levelRequirement: 5,
    hp: 220,
    maxHp: 220,
    attack: 18,
    defense: 8,
    experience: 220,
    gold: 100,
    drops: ["robe"],
    img: "img/enemies/wyvern.webp",
  },
  treasure_guardian: {
    type: "Treasure Guardian",
    levelRequirement: 5,
    hp: 350,
    maxHp: 350,
    attack: 25,
    defense: 20,
    magicAttack: 20,
    experience: 350,
    gold: 100,
    drops: ["chainmail", "divine_sword", "plate_armor"],
    img: "img/enemies/treasure_guardian.webp",
  },
  beholder: {
    type: "Beholder",
    levelRequirement: 5,
    hp: 100,
    maxHp: 100,
    attack: 20,
    defense: 7,
    experience: 100,
    gold: 70,
    drops: ["katana"],
    img: "img/enemies/beholder.webp",
  },

  zombie: {
    type: "Zombie",
    levelRequirement: 2,
    hp: 50,
    maxHp: 50,
    attack: 10,
    defense: 3,
    experience: 40,
    gold: 20,
    drops: ["big_health_potion"],
    img: "img/enemies/zombie.webp",
  },
  vampire: {
    type: "Vampire",
    levelRequirement: 3,
    hp: 150,
    maxHp: 150,
    attack: 15,
    defense: 5,
    experience: 150,
    gold: 30,
    drops: ["elixir_potion"],
    img: "img/enemies/vampire.webp",
  },
  squeletor: {
    narratorLine: "El esqueleto alza su arma con una convicción que, técnicamente, no debería tener: le faltan la mayoría de los músculos necesarios para sostenerla.",
    type: "Squeletor",
    levelRequirement: 2,
    hp: 70,
    maxHp: 70,
    attack: 12,
    defense: 4,
    experience: 55,
    gold: 25,
    drops: ["hammer"],
    img: "img/enemies/squeletor.webp",
  },
  warlock: {
    type: "Warlock",
    levelRequirement: 3,
    hp: 90,
    maxHp: 90,
    attack: 14,
    defense: 6,
    magicAttack: 18,
    experience: 70,
    gold: 35,
    drops: ["wand"],
    img: "img/enemies/warlock.webp",

  },
  imp: {
    type: "Imp",
    levelRequirement: 2,
    hp: 40,
    maxHp: 40,
    attack: 8,
    defense: 2,
    experience: 30,
    gold: 15,
    drops: ["gown"],
    img: "img/enemies/imp.webp",
  },
  linchorn: {
    type: "Linchorn",
    levelRequirement: 5,
    hp: 210,
    maxHp: 210,
    attack: 20,
    defense: 8,
    experience: 210,
    gold: 45,
    drops: ["katana"],
    img: "img/enemies/linchorn.webp",
  },
  hydra: {
    type: "Hydra",
    levelRequirement: 6,
    hp: 550,
    maxHp: 550,
    attack: 25,
    defense: 18,
    experience: 550,
    gold: 200,
    drops: ["plate_armor"],
    img: "img/enemies/hydra.webp",
  },
  centaurus: {
    type: "Centaurus",
    levelRequirement: 5,
    hp: 130,
    maxHp: 130,
    attack: 18,
    defense: 7,
    experience: 100,
    gold: 55,
    drops: ["elemental_wand"],
    img: "img/enemies/centaurus.webp",
  },
  chimera: {
    type: "Chimera",
    levelRequirement: 6,
    hp: 440,
    maxHp: 440,
    attack: 20,
    defense: 10,
    experience: 440,
    gold: 158,
    drops: ["divine_sword"],
    img: "img/enemies/chimera.webp",
  },
  cultist: {
    type: "Cultist",
    levelRequirement: 4,
    hp: 85,
    maxHp: 85,
    attack: 13,
    defense: 5,
    magicAttack: 15,
    experience: 75,
    gold: 38,
    drops: ["bless_staff"],
    img: "img/enemies/cultist.webp",
  },
  drider: {
    type: "Drider",
    levelRequirement: 5,
    hp: 320,
    maxHp: 320,
    attack: 17,
    defense: 6,
    experience: 300,
    gold: 142,
    drops: ["arcane_robe"],
    img: "img/enemies/drider.webp",
  },
  kraken: {
    type: "Kraken",
    levelRequirement: 10,
    hp: 550,
    maxHp: 550,
    attack: 50,
    defense: 32,
    magicAttack: 20,
    experience: 550,
    gold: 220,
    drops: ["trident", "sea_armor"],
    img: "img/enemies/kraken.webp",
  },
  sea_serpent: {
    type: "Sea Serpent",
    levelRequirement: 9,
    hp: 390,
    maxHp: 390,
    attack: 27,
    defense: 10,
    magicAttack: 18,
    experience: 390,
    gold: 200,
    drops: ["water_staff", "aqua_robe"],
    img: "img/enemies/sea_serpent.webp",
  },
  medusa: {
    type: "Medusa",
    levelRequirement: 8,
    hp: 360,
    maxHp: 360,
    attack: 25,
    defense: 15,
    magicAttack: 30,
    experience: 360,
    gold: 280,
    drops: ["serpent_sword", "stone_armor"],
    img: "img/enemies/medusa.webp",
  },
  mermaid: {
    type: "Mermaid",
    levelRequirement: 7,
    hp: 440,
    maxHp: 440,
    attack: 22,
    defense: 8,
    magicAttack: 24,
    experience: 440,
    gold: 170,
    drops: ["ocean_staff", "coral_robe"],
    img: "img/enemies/mermaid.webp",
  },
  pirate: {
    type: "Pirate",
    levelRequirement: 6,
    hp: 200,
    maxHp: 200,
    attack: 21,
    defense: 7,
    experience: 220,
    gold: 150,
    drops: ["cutlass", "leather_armor"],
    img: "img/enemies/pirate.webp",
  },
  pirate_captain: {
    type: "Pirate Captain",
    levelRequirement: 8,
    hp: 370,
    maxHp: 370,
    attack: 26,
    defense: 9,
    experience: 300,
    gold: 190,
    drops: ["captain_sword", "captain_coat"],
    img: "img/enemies/pirate_captain.webp",
  },
  Inferno_elemental: {
    type: "Inferno Elemental",
    levelRequirement: 9,
    hp: 280,
    maxHp: 280,
    attack: 28,
    defense: 11,
    magicAttack: 25,
    experience: 320,
    gold: 210,
    drops: ["flame_staff", "fire_robe"],
    img: "img/enemies/inferno_elemental.webp",
  },
  gorilla_warrior: {
    type: "Gorilla Warrior",
    levelRequirement: 7,
    hp: 220,
    maxHp: 220,
    attack: 23,
    defense: 8,
    experience: 240,
    gold: 160,
    drops: ["giant_club", "jungle_armor"],
    img: "img/enemies/gorilla_warrior.webp",
  },
  jungle_tiger: {
    type: "Jungle Tiger",
    levelRequirement: 6,
    hp: 210,
    maxHp: 210,
    attack: 20,
    defense: 7,
    experience: 230,
    gold: 155,
    drops: ["tiger_blade", "leather_armor"],
    img: "img/enemies/jungle_tiger.webp",
  },
  vine_serpent: {
    type: "Vine Serpent",
    levelRequirement: 8,
    hp: 250,
    maxHp: 250,
    attack: 24,
    defense: 9,
    magicAttack: 20,
    experience: 270,
    gold: 175,
    drops: ["vine_whip", "nature_robe"],
    img: "img/enemies/vine_serpent.webp",
  },
  jungle_spirit: {
    type: "Jungle Spirit",
    levelRequirement: 9,
    hp: 300,
    maxHp: 300,
    attack: 29,
    defense: 10,
    magicAttack: 28,
    experience: 330,
    gold: 215,
    drops: ["spirit_staff", "ethereal_robe"],
    img: "img/enemies/jungle_spirit.webp",
  },
  diablo: {
    type: "Diablo",
    levelRequirement: 10,
    hp: 750,
    maxHp: 750,
    attack: 52,
    defense: 33,
    magicAttack: 50,
    experience: 700,
    gold: 350,
    drops: ["demon_blade", "dark_armor"],
    img: "img/enemies/diablo.webp",
  },
  dragon: {
    type: "Dragon",
    levelRequirement: 10,
    hp: 1000,
    maxHp: 1000,
    attack: 55,
    defense: 40,
    magicAttack: 52,
    experience: 800,
    gold: 400,
    drops: ["ring_of_knowledge", "staff", "robe"],
    img: "img/enemies/dragon.webp",
  },

  // SPEC-1108: Kestrel, el rival recurrente — duelo único si el jugador no
  // lo ayudó ni lo traicionó lo suficiente en sus 2 apariciones previas.
  kestrel_rival: {
    type: "Kestrel",
    levelRequirement: 10,
    hp: 400,
    maxHp: 400,
    attack: 45,
    defense: 18,
    experience: 350,
    gold: 150,
    drops: ["health_potion"],
    img: "img/enemies/thief.webp",
  },

  // SPEC-1219 — Valdris, antagonista real (Fase 1 del plan
  // docs/PLAN-HISTORIA-FASE4.md). Se pelea justo antes de dragon_king (ver
  // valdrisArc.js + combatRewards.js, que encadena el combate del Rey
  // Dragón inmediatamente después de esta victoria). Stats entre el último
  // boss del Acto II (frost_wyrm ~hp880/atk44) y dragon_king (hp3000/atk100):
  // mago puro, magicAttack por encima de su ataque físico.
  valdris_corrupted: {
    isBoss: true,
    type: "Valdris",
    levelRequirement: 10,
    hp: 1600,
    maxHp: 1600,
    attack: 55,
    defense: 28,
    magicAttack: 70,
    experience: 1500,
    gold: 400,
    introLine: "—¡Solo quería protegerlos de lo que él podía volver a ser!",
    deathMessage: "Solo... quería ser yo quien lo sostuviera con cuidado...",
    img: "img/enemies/valdris_corrupted.webp",
  },

  dragon_king: {
    isBoss: true,
    type: "Dragon",
    levelRequirement: 10,
    hp: 3000,
    maxHp: 3000,
    attack: 100,
    defense: 50,
    magicAttack: 50,
    experience: 3000,
    gold: 1000,
    drops: ["saint_grial", "excalibur", "dragon_heart"],
    deathMessage: "Gracias... por recordarme.",
    img: "img/enemies/dragon_king.webp",
  },

  genie: {
    type: "Genie",
    levelRequirement: 10,
    hp: 250,
    maxHp: 250,
    attack: 20,
    defense: 5,
    magicAttack: 40,
    experience: 300,
    gold: 200,
    drops: ["ring_of_wisdom", "magic_lamp"],
    img: "img/enemies/genie.webp",
  },

  gremlin: {
    type: "Gremlin",
    levelRequirement: 4,
    hp: 75,
    maxHp: 75,
    attack: 14,
    defense: 4,
    experience: 65,
    gold: 28,
    drops: ["dagger"],
    img: "img/enemies/gremlin.webp",
  },

  dwarf_warrior: {
    type: "Dwarf Warrior",
    levelRequirement: 4,
    hp: 95,
    maxHp: 95,
    attack: 16,
    defense: 6,
    experience: 70,
    gold: 32,
    drops: ["war_hammer"],
    img: "img/enemies/dwarf_warrior.webp",
  },

  pegasus: {
    type: "Pegasus",
    levelRequirement: 3,
    hp: 130,
    maxHp: 130,
    attack: 18,
    defense: 5,
    experience: 100,
    gold: 50,
    drops: ["light_armor"],
    img: "img/enemies/pegasus.webp",
  },

  tent: {
    type: "Tent",
    levelRequirement: 5,
    hp: 210,
    maxHp: 210,
    attack: 15,
    defense: 7,
    experience: 200,
    gold: 100,
    drops: ["healing_staff"],
    img: "img/enemies/tent.webp",
  },

  dark_knight: {
    type: "Dark Knight",
    levelRequirement: 7,
    hp: 260,
    maxHp: 260,
    attack: 22,
    defense: 15,
    experience: 300,
    gold: 60,
    drops: ["dark_sword", "dark_shield"],
    img: "img/enemies/dark_knight.webp",
  },

  sand_worm: {
    type: "Sand Worm",
    levelRequirement: 8,
    hp: 200,
    maxHp: 200,
    attack: 25,
    defense: 8,
    experience: 200,
    gold: 70,
    drops: ["desert_armor"],
    img: "img/enemies/sand_worm.webp",
  },

  lava_golem: {
    type: "Lava Golem",
    levelRequirement: 9,
    hp: 220,
    maxHp: 220,
    attack: 28,
    defense: 10,
    experience: 220,
    gold: 80,
    drops: ["lava_sword", "fire_shield"],
    img: "img/enemies/lava_golem.webp",
  },

  pyro_elemental: {
    type: "Pyro Elemental",
    levelRequirement: 10,
    hp: 350,
    maxHp: 350,
    attack: 30,
    defense: 12,
    magicAttack: 35,
    experience: 350,
    gold: 90,
    drops: ["pyro_staff", "flame_robe"],
    img: "img/enemies/pyro_elemental.webp",

  },

  inferno_dragon: {
    isBoss: true,
    type: "Inferno Dragon",
    levelRequirement: 10,
    hp: 1000,
    maxHp: 1000,
    attack: 50,
    defense: 15,
    magicAttack: 30,
    experience: 800,
    gold: 800,
    drops: ["inferno_blade", "dragon_scale_armor"],
    deathMessage: "Mi... ira... se apaga...",
    // SPEC-1223: narrador oculto, línea 7/7 — la más personal, sin introLine
    // previo del que heredar tono (este jefe no tenía uno). Última línea
    // antes del silencio total en el Rey Dragón.
    narratorLine: "Ya casi no queda distancia entre lo que cuento y lo que soy. Si llegás hasta el final de este camino, vas a entender por qué he estado tan callado sobre quién habla en verdad.",
    img: "img/enemies/inferno_dragon.webp",
  },


  //bosses
  forest_titan: {
    // SPEC-1101: tanque de guardia -- ATK/magicAttack bajos (no necesita
    // pegar fuerte, su guardia de raíces hace el trabajo defensivo), HP
    // alto porque la pelea se alarga mientras el jugador rompe la guardia.
    isBoss: true,
    type: "Forest Titan",
    levelRequirement: 8,
    hp: 950,
    maxHp: 950,
    attack: 32,
    defense: 18,
    magicAttack: 15,
    experience: 800,
    gold: 120,
    drops: ["titan_branch", "inferno_blade"],
    // introLine/epilogueLines: SPEC-1218 — capitulo 1 de "historia mejorada"
    // (ver memoria project_equipment_window... no, project_narrative_v2).
    // deathMessage NO se toca: mq_02_los_sellos lo cita textual en su dialogo
    // "completed" (quests.js) — cambiarlo desincroniza esa cita.
    introLine: "—Quedaos... Esta vez, quedaos...",
    // SPEC-1223: narrador oculto, línea 1/7 — el más distante de los siete.
    narratorLine: "El bosque guarda silencio mientras avanzas. Algo muy viejo duerme bajo estas raíces — y sueña, todavía, con ser libre.",
    deathMessage: "El dragón... está llorando...",
    epilogueLines: [
      "El dragón no está despertando. Está soñando que aún vive.",
      "Cuando el bosque vuelve a respirar, Oakhaven celebra hasta el amanecer. Alguien deja en tu mochila una pequeña figura de madera con forma de dragón."
    ],
    img: "img/enemies/forest_titan.webp",
  },
  cave_devourer: {
    // SPEC-1101: brutal de golpe fuerte y bajo HP relativo -- la amenaza real
    // es "devorar" cada 3er turno, no el desgaste normal.
    isBoss: true,
    type: "Cave Devourer",
    levelRequirement: 8,
    hp: 780,
    maxHp: 780,
    attack: 46,
    defense: 12,
    magicAttack: 10,
    experience: 800,
    gold: 120,
    drops: ["devourer_fang", "inferno_blade"],
    introLine: "—Silencio... No quiero oír otra vez la sentencia...",
    // SPEC-1223: narrador oculto, línea 2/7 — primer desliz sutil (habla en primera persona de algo que "escuchó").
    narratorLine: "Estas cuevas han tragado gritos durante mil años. Yo... los he escuchado todos. No sé por qué lo recuerdo tan bien.",
    deathMessage: "No... quería... que me olvidaran...",
    epilogueLines: [
      "En lo más profundo de la caverna, una inscripción tallada tiembla bajo tus dedos: «Ocho no fueron las cadenas que el dragón creó. Ocho fueron las cadenas con que lo atamos.» Junto a ella, un emblema — idéntico al medallón que Elara lleva siempre al cuello."
    ],
    img: "img/enemies/cave_devourer.webp",
  },
  mountain_colossus: {
    // SPEC-1101: tanque puro -- HP alto, ATK moderado (su coraza pétrea de
    // 50% físico ya hace la mayor parte del trabajo defensivo).
    isBoss: true,
    type: "Mountain Colossus",
    levelRequirement: 8,
    hp: 1000,
    maxHp: 1000,
    attack: 38,
    defense: 22,
    magicAttack: 10,
    experience: 800,
    gold: 120,
    drops: ["earthbreaker_core", "inferno_blade"],
    introLine: "—No puedo caer. Lo juré. No puedo...",
    // SPEC-1223: narrador oculto, línea 3/7 — el desliz explícito del pitch original.
    narratorLine: "Asterion levantó estas montañas con sus propias... No. Eso solo lo cuentan las leyendas. ¿O no?",
    deathMessage: "Seguí... de pie... hasta el final...",
    epilogueLines: [
      "Por un instante, su recuerdo se abre ante ti: Asterion frente a ejércitos humanos, su voz haciendo temblar las montañas. «Si vuestra libertad solo sirve para mataros, os libraré de ella.»"
    ],
    img: "img/enemies/mountain_colossus.webp",
  },
  ancient_construct: {
    // SPEC-1101: glass cannon mágico -- HP/DEF bajos, magicAttack alto (usa
    // "mage" behavior + sobrecarga cada 4 turnos); castiga no defenderse.
    isBoss: true,
    type: "Ancient Construct",
    levelRequirement: 8,
    hp: 720,
    maxHp: 720,
    attack: 25,
    defense: 10,
    magicAttack: 42,
    experience: 800,
    gold: 120,
    drops: ["construct_eye", "ancient_relic"],
    // deathMessage NO se toca: mq_04_la_verdad lo cita textual en "completed".
    introLine: "—Identidad no reconocida. Protocolo de purga: iniciado.",
    // SPEC-1223: narrador oculto, línea 4/7 — más incómodo, admite haber aprendido algo que ya no recuerda de dónde.
    narratorLine: "Este lugar sabe mentir con hechos verdaderos. Lo sé porque yo también aprendí a hacerlo, hace mucho tiempo — aunque ya no recuerdo de quién aprendí.",
    deathMessage: "Asterion no destruye el mundo. El mundo lo está matando. Busca... la Puerta del Dragón...",
    epilogueLines: [
      "Los ocho sellos no guardan el poder de Asterion. Guardan los recuerdos que la humanidad le arrancó. Sin ellos, el dragón no sabe quién fue — solo siente sus emociones separadas: hambre, hielo, miedo, ira.",
      "Antes de que el Constructo termine de hablar, una descarga arcana lo hace pedazos. El rastro de esa magia se pierde hacia la Torre del Castillo."
    ],
    img: "img/enemies/ancient_construct.webp",
  },
  swamp_abomination: {
    // SPEC-1101: presión sostenida -- ATK/DEF moderados, la amenaza real es
    // el veneno acumulativo, no el golpe directo.
    isBoss: true,
    type: "Swamp Abomination",
    levelRequirement: 8,
    hp: 850,
    maxHp: 850,
    attack: 34,
    defense: 16,
    magicAttack: 20,
    experience: 800,
    gold: 120,
    drops: ["abomination_core", "inferno_blade"],
    introLine: "—Quedate... Aquí nadie te decepciona... Aquí nadie se va...",
    // SPEC-1223: narrador oculto, línea 5/7 — confunde su propia voz entre las voces atrapadas.
    narratorLine: "Tantas voces atrapadas aquí, todas suplicando ser escuchadas. A veces, en medio del pantano, olvido cuál de esas voces era la mía.",
    deathMessage: "Ya no hay... esperanza... para mí...",
    epilogueLines: [
      "Por un instante, miles de voces recuperan su nombre. Entre ellas, una que suena antigua, casi ceremonial: «No salvamos el mundo. Solo hicimos que olvidara nuestro crimen.»",
      "Esa voz pertenecía a la fundadora de la Orden del Primer Canto — la misma orden a la que Elara ha servido toda su vida."
    ],
    img: "img/enemies/swamp_abomination.webp",
  },

  // SPEC-1005 — mini-bosses nuevos (sin equivalente cercano existente)
  stone_charger: {
    type: "Stone Charger",
    levelRequirement: 6,
    hp: 350,
    maxHp: 350,
    attack: 28,
    defense: 14,
    experience: 350,
    gold: 90,
    drops: ["axe"],
    img: "img/enemies/mountain_giant.webp",
  },
  ice_giant: {
    type: "Ice Giant",
    levelRequirement: 6,
    hp: 400,
    maxHp: 400,
    attack: 26,
    defense: 16,
    experience: 400,
    gold: 95,
    drops: ["glacial_core"],
    img: "img/enemies/mountain_giant.webp",
  },
  frozen_spirit: {
    type: "Frozen Spirit",
    levelRequirement: 6,
    hp: 280,
    maxHp: 280,
    attack: 14,
    defense: 6,
    magicAttack: 26,
    experience: 300,
    gold: 85,
    drops: ["arcane_robe"],
    img: "img/enemies/drider.webp",
  },

  frost_wyrm: {
    // SPEC-1101: híbrido físico/mágico -- congela la magia del jugador cada
    // 3er turno, así que su propio ataque es principalmente físico fuerte.
    isBoss: true,
    type: "Frost Wyrm",
    levelRequirement: 8,
    hp: 880,
    maxHp: 880,
    attack: 44,
    defense: 17,
    magicAttack: 25,
    experience: 800,
    gold: 120,
    drops: ["wyrm_tail", "glacial_core"],
    introLine: "—Vendrá... mañana...",
    // SPEC-1223: narrador oculto, línea 6/7 — casi confiesa que cuenta el tiempo "desde adentro".
    narratorLine: "Mil años de espera. Sé exactamente cuánto pesa esa cifra. La cuento desde adentro, no desde afuera — y no sé desde cuándo dejé de notar la diferencia.",
    deathMessage: "Mil años... esperando... que alguien volviera...",
    epilogueLines: [
      "En el centro de la tundra, un recuerdo se abre: un niño llamado Cael prometió volver para ver las estrellas junto a Asterion. Volvió siendo anciano, pero unos soldados le impidieron llegar. Asterion nunca lo supo.",
      "El hielo se resquebraja y libera un amanecer que llevaba mil años detenido."
    ],
    img: "img/enemies/frost_wyrm.webp",
  },

};