// locations.js
export const worldMap = {
  town: {
    id: "town",
    name: "Town Square",
    description: "You are in the town square. Villagers bustle around. The air smells of fresh bread and adventure.",
    exits: { east: "shop", north: "forest", west: "tavern", south: "training_grounds" },
    canRest: true,
  },
  shop: {
    id: "shop",
    name: "General Store",
    description: "A small shop filled with goods. Shelves are packed with potions, weapons, and curious artifacts.",
    exits: { west: "town" },
  },
  tavern: {
    id: "tavern",
    name: "The Drunken Dragon",
    description: "A cozy tavern filled with adventurers. The smell of ale and roasted meat fills the air.",
    exits: { east: "town", north: "alley" },
    canRest: true,
  },
  alley: {
    id: "alley",
    name: "Dark Alley",
    description: "A narrow, shadowy alley. You feel like you're being watched...",
    exits: { south: "tavern" },
    enemies: ["thief"],
  },
  training_grounds: {
    id: "training_grounds",
    name: "Training Grounds",
    description: "Where warriors hone their skills. Dummies and practice weapons are scattered around.",
    exits: { north: "town", east: "barracks" },
  },
  barracks: {
    id: "barracks",
    name: "Royal Barracks",
    description: "The king's soldiers train here. The air is filled with the sound of clashing steel.",
    exits: { west: "training_grounds" },
    enemies: ["guard"],
  },
  forest: {
    id: "forest",
    name: "Dark Forest",
    description: "The forest is dense and filled with danger. Ancient trees block most of the sunlight.",
    exits: { south: "town", east: "cave", north: "deep_forest", west: "river" },
    enemies: ["goblin", "wolf", "slime"],
  },
  deep_forest: {
    id: "deep_forest",
    name: "Deep Forest",
    description: "The heart of the forest. The trees are enormous and the air is thick with magic.",
    exits: { south: "forest", east: "ancient_ruins" },
    enemies: ["wolf", "orc", "fungedBeast"],
  },
  ancient_ruins: {
    id: "ancient_ruins",
    name: "Ancient Ruins",
    description: "Crumbling stone structures covered in vines. Something powerful sleeps here...",
    exits: { west: "deep_forest", down: "underground_temple" },
    enemies: ["orc", "goblin_shaman"],
  },
  underground_temple: {
    id: "underground_temple",
    name: "Underground Temple",
    description: "A mysterious temple buried deep underground. Strange runes glow on the walls.",
    exits: { up: "ancient_ruins", east: "sacred_chamber" },
    enemies: ["stone_golem", "ancient_guardian"],
  },
  sacred_chamber: {
    id: "sacred_chamber",
    name: "Sacred Chamber",
    description: "The innermost chamber of the temple. A powerful energy emanates from the center.",
    exits: { west: "underground_temple" },
    enemies: ["dragon"],
  },
  river: {
    id: "river",
    name: "Crystal River",
    description: "A sparkling river that cuts through the forest. The water looks clean and refreshing.",
    exits: { east: "forest", north: "waterfall" },
  },
  waterfall: {
    id: "waterfall",
    name: "Hidden Waterfall",
    description: "A majestic waterfall hides a secret cave behind its curtain of water.",
    exits: { south: "river", enter: "hidden_cave" },
  },
  hidden_cave: {
    id: "hidden_cave",
    name: "Hidden Cave",
    description: "A secret cave behind the waterfall. Treasure might be hidden here!",
    exits: { out: "waterfall" },
    enemies: ["cave_bear", "treasure_guardian"],
  },
  cave: {
    id: "cave",
    name: "Shadow Cave",
    description: "A dark cave where orcs dwell. The sound of dripping water echoes through the tunnels.",
    exits: { west: "forest", north: "mountain", south: "cave_depths" },
    enemies: ["orc", "cave_bat"],
  },
  cave_depths: {
    id: "cave_depths",
    name: "Cave Depths",
    description: "The deepest part of the cave. It's pitch black and smells of damp earth.",
    exits: { north: "cave" },
    enemies: ["giant_spider", "cave_troll"],
  },
  mountain: {
    id: "mountain",
    name: "Dragon's Peak",
    description: "The treacherous path to the dragon's lair. The air is thin and cold.",
    exits: { south: "cave", summit: "dragon_lair" },
    enemies: ["mountain_giant", "wyvern"],
  },
  dragon_lair: {
    id: "dragon_lair",
    name: "Dragon's Lair",
    description: "The final challenge. The dragon's hoard glitters in the dim light.",
    exits: { down: "mountain" },
    enemies: ["dragon"],
  },
  garden: {
    id: "garden",
    name: "Garden",
    description: "A majestic waterfall hides a secret cave behind its curtain of water.",
    exits: { east: "forest", enter: "hidden_cave" },
  },
  dungeon: {
    id: "dungeon",
    name: "Dungeon Entrance",
    description: "A dark and foreboding entrance to an ancient dungeon. Danger lurks within.",
    exits: { out: "mountain" },
    enemies: ["squeletor", "zombie", "vampire"],
  },
  inferno: {
    id: "inferno",
    name: "Inferno Volcano",
    description: "A raging volcano filled with molten lava and fiery creatures. Only the bravest dare enter.",
    exits: { out: "volcano" },
    enemies: ["inferno_dragon", "lava_golem", "diablo"],
  },

};